stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw
  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
    - data/raw
    - src/data_preprocessing.py

    outs:
    - data/interdim

  model_training:
    cmd: python src/model_training.py
    deps:
    - data/interdim
    - src/model_training.py
    params:
    - model_training.n_estimators
    - model_training.random_state
    outs:
    - model/model.pkl

  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
    - data/interdim
    - src/model_evaluation.py
    - model/model.pkl

    outs:
    - reports/metrics.json